# ——— Site basics ———
title: "Grey Kuling, Ph.D."
description: "Curriculum & Research Fellow — Harvard Medical School. "
url: "https://gkuling.github.io"   # your GitHub Pages domain (no trailing slash)
baseurl: "/gk-site"                 # your repository project name (with leading slash)

# ——— Theme ———
theme: just-the-docs
color_scheme: light   # light | dark

# Show your logo in the header (optional)
#logo: "/assets/img/profile_casual.jpg"

# Search configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  rel_url: true
  button: false
  focus_shortcut_key: "k"

# Navigation tweaks
nav_sort: case_insensitive

# Aux links (top-right)
aux_links:
  "GitHub": https://github.com/gkuling
  "ORCID": https://orcid.org/0000-0002-8742-6586

# Footer and edit links
footer_content: "© 2026 Grey Kuling. Built with Just the Docs."
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y"
# gh_edit_link: true
# gh_edit_repository: https://github.com/<user>/<repo>
# gh_edit_branch: main

# Collections (optional future expansion)
# collections:
#   research:
#     output: true

plugins:
  - jekyll-redirect-from